### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by DoisPontinhos** [jspenaq/LolSapiens#28]
Hey, I'm new to this and I'm getting this error when running "npm run dev"

npm ERR! Missing script: "dev"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

**Comment by Anvido** [comment]
@DoisPontinhos  Sorry, The project is in development, so we are updating the repo. But at some point, you can try to run the npm commands by checking the package.json file. And remember to run the npm scripts under the same package.json folder (frontend or desktop)
