### ISSUE TITLE
npm ERR! Missing script: "dev"

### ISSUE THREAD

**Issue by Kerboyy** [jspenaq/LolSapiens#30]
somebody can help me with this?

npm ERR! Missing script: "dev"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rados\AppData\Local\npm-cache\_logs\2023-02-26T01_26_47_498Z-debug-0.log

**Comment by jspenaq** [comment]
Can you please copy and paste the logs?
Which commands did you run?

**Comment by jspenaq** [comment]
Readme updated
